### ISSUE TITLE
Increase Dicrease puzzle array size

### ISSUE THREAD

**Issue by yasirwahid** [cawfree/react-native-picture-puzzle#3]
i really liked your work, i need to customize your puzzle a bit. working on some levels. so i need to add more and less pieces of array to it. couldnt find any success. any guide would be appreciated.

Thanks.

Solved. thabnks for the amazing code buddy.

**Comment by salmanafzal775** [comment]
Hello Yasir,
i am also trying to do this can you please tell me how you increase the size?
and also can i change the dimensions like 6 column and 9 rows?
